// generated by tjscli: ts-json-schema-generator
import { JSONSchema7 } from 'json-schema';

const IPokemon: JSONSchema7 = {
  $schema: 'http://json-schema.org/draft-07/schema#',
  type: 'object',
  properties: {
    id: { type: 'number', description: 'pokemon id' },
    is_default: { type: 'boolean' },
    base_experience: { type: 'number' },
    height: { type: 'number', description: 'pokemon height' },
    location_area_encounters: { type: 'string' },
    name: { type: 'string' },
    order: { type: 'number' },
    species: {
      type: 'object',
      properties: { name: { type: 'string' }, url: { type: 'string' } },
      required: ['name', 'url'],
    },
  },
  required: [
    'id',
    'is_default',
    'base_experience',
    'height',
    'location_area_encounters',
    'name',
    'order',
    'species',
  ],
};
export default IPokemon;
