// generated by tjscli: ts-json-schema-generator
import { JSONSchema7 } from 'json-schema';

const IReqPokeDetail: JSONSchema7 = {
  $schema: 'http://json-schema.org/draft-07/schema#',
  type: 'object',
  properties: {
    Querystring: {
      type: 'object',
      properties: {
        tid: { type: 'string', description: 'transaction id on each request', format: 'uuid' },
      },
      required: ['tid'],
    },
    Params: {
      type: 'object',
      properties: { name: { type: 'string', description: 'Pokemon name' } },
      required: ['name'],
    },
  },
  required: ['Querystring', 'Params'],
};
export default IReqPokeDetail;
